name: Morchana static qr code api

on:
  push:
    branches:
      - master

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-18.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - uses: actions/checkout@v2
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: init
          tf_actions_working_dir: ./terraform/production/app/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Terraform Plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: plan
          tf_actions_working_dir: ./terraform/production/app/
          args: |
            -out=plan.tfplan
            -var="access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}"
            -var="secret_access_id=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            -var="infrastructure_version=${GITHUB_SHA::8}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Terraform Destroy
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: destroy
          tf_actions_working_dir: ./terraform/production/app/
          args: |
            -var="access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}"
            -var="secret_access_id=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            -var="infrastructure_version=${GITHUB_SHA::8}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}