name: Workflow for tags

on:
  push:
    branches: master
    tags: '*'

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
    - name: test
      run: |
        echo "atb"
        echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
