name: Morchana Static QR Code API

on:
  push:
    branches:
      - master

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-18.04
    steps:
      - name: Authen AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo $GITHUB_SHA
          eval $(aws ecr get-login --no-include-email --region ap-southeast-1)
          aws s3 ls
          aws --version
          aws configure list