name: Morchana Static QR Code API

on:
  push:
    branches:
      - master

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-18.04
    steps:
          # echo $GITHUB_SHA
          # eval $(aws ecr get-login --no-include-email --region ap-southeast-1)
          # aws s3 ls
          # aws --version
          # aws configure list
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    - name: Copy files to S3 with the AWS CLI
      run: |
        aws s3 ls