name: Morchana Static QR Code API

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test SHA
      run: |
        echo $(echo ${GITHUB_SHA} | cut -c1-8)
        echo $ATB