name: Morchana Static QR Code API

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    env:
      ATB: GITHUB_SHA

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test SHA
      run: |
        echo $(echo ${GITHUB_SHA} | cut -c1-8)
        echo ${GITHUB_SHA:7}
        echo ${GITHUB_SHA:8}
        echo ${GITHUB_SHA:0:8}
        echo "SHA"
        echo $ATB